version: 2.1
defaults: &defaults
  working_directory: ~/user-data-for-fraud-prevention
  docker:
    - image: circleci/node:10.15.3-browsers
  environment:
    TZ: '/usr/share/zoneinfo/America/Los_Angeles'
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: *yarn
      - save_cache: *save-cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    <<: *defaults
    - attach_workspace:
      at: ~/user-data-for-fraud-prevention
    steps:

      # run build
      - run: yarn run build

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/user-data-for-fraud-prevention
      - run: yarn run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/user-data-for-fraud-prevention
      - run: yarn run tes
      # run tests and generate coverage
      - run:
          name: "Run tests and generate coverage report"
          command: yarn run test:coverage

      - store_artifacts:
          path: coverage

  pr-check:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/user-data-for-fraud-prevention
      - run:
          name: Check PR for semantic version label
          command: yarn auto pr-check --pr $CHANGE_ID --url $CIRCLE_BUILD_URL

  release:
    <<: *defaults
    steps:
      - attach_workspace:
          at:  ~/user-data-for-fraud-prevention
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Release
          command: yarn auto shipit

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}

workflows:
  version: 2
  build_and_test:
    jobs:
      - install

      - build:
          requires:
            - install

      - lint:
          requires:
            - build

      - test:
          requires:
            - build

      - pr-check:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master

      - release:
          requires:
            - test
            - lint
